### ISSUE TITLE
Publishing the plugin to Open VSX

### ISSUE THREAD

**Issue by cyChop** [paulbarre/vscode-klavaro#7]
Only Visual Studio products can use the VS Code marketplace. However, several open source solutions support VS Code extensions. [That's why Open VSX was created][openvsx]. Making Klavaro available in this marketplace would make it easier to use for people who don't want to use Microsoft products.

There are two publication methods (either through npx or through creating a pull request to https://github.com/open-vsx/publish-extensions). Both are explained on the [page linked earlier][openvsx].

Thanks for this extension!

[openvsx]: https://www.gitpod.io/blog/open-vsx/

**Comment by paulbarre** [comment]
Hi!
I didn't know about Open VSX! Thank you for the comment.
I will publish Klavaro there very soon.

**Comment by paulbarre** [comment]
You can now found Klavaro on Open VSX.
https://open-vsx.org/extension/paulbarre/klavaro

Thanks again for your suggestion. @cyChop
